SELECT A.CATEGORY, A.MAX_PRICE, B.PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE  -- 카테고리별 최대 가격
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) AS A, FOOD_PRODUCT AS B
WHERE B.PRICE = A.MAX_PRICE AND A.CATEGORY = B.CATEGORY
ORDER BY A.MAX_PRICE DESC;
