SELECT A.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) HALF_TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR) A
    JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR) B
    ON A.FLAVOR = B.FLAVOR
ORDER BY HALF_TOTAL+JULY_TOTAL DESC
LIMIT 3
