SELECT
    PRICE - PRICE % 10000 PRICE_GROUP, -- 만원 단위 구하는 방법 1
    FLOOR(PRICE / 10000) * 10000 PRICE_GROUP, -- 만원 단위 구하는 방법 2
    COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP
