SELECT A.USER_ID,
    A.NICKNAME,
    SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_USER A JOIN USED_GOODS_BOARD B
ON A.USER_ID = B.WRITER_ID
WHERE B.STATUS = 'DONE'
GROUP BY 1
HAVING SUM(B.PRICE) >= 700000
ORDER BY 3
