SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, LEFT(B.CREATED_DATE, 10)
FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID  -- 게시글 ID 기준 JOIN
WHERE LEFT(A.CREATED_DATE, 7) = '2022-10'
ORDER BY B.CREATED_DATE, A.TITLE  -- 댓글 작성일 기준 정렬
