SELECT B.AUTHOR_ID,
    C.AUTHOR_NAME,
    B.CATEGORY,
    SUM(A.SALES * B.PRICE) TOTAL_SALES
FROM BOOK_SALES A JOIN BOOK B
    ON A.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR C
    ON B.AUTHOR_ID = C.AUTHOR_ID
WHERE LEFT(A.SALES_DATE, 7) = '2022-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY C.AUTHOR_ID ASC, B.CATEGORY DESC
